/** Generated by YAKINDU Statechart Tools code generator. */

#ifndef MICROONDAS_REQUIRED_H_
#define MICROONDAS_REQUIRED_H_

#include "../src/sc_types.h"
#include "Microondas.h"

#ifdef __cplusplus
extern "C"
{
#endif 

/*! \file
This header defines prototypes for all functions that are required by the state machine implementation.

This is a state machine uses time events which require access to a timing service. Thus the function prototypes:
- microondas_set_timer and
- microondas_unset_timer
are defined.
This state machine makes use of operations declared in the state machines interface or internal scopes. Thus the function prototypes:
- microondas_play
- microondas_display
- microondas_deciamlPoint
- microondas_displayapagado
- microondas_selector
are defined.

These functions will be called during a 'run to completion step' (runCycle) of the statechart. 
There are some constraints that have to be considered for the implementation of these functions:
- never call the statechart API functions from within these functions.
- make sure that the execution time is as short as possible.

*/

extern void microondas_play(const Microondas* handle, const uint16_t vPeriodo, const uint16_t vDuracion);
extern void microondas_display(const Microondas* handle, const uint8_t d3, const uint8_t d2, const uint8_t d1, const uint8_t d0);
extern void microondas_deciamlPoint(const Microondas* handle, const uint8_t dp);
extern void microondas_displayapagado(const Microondas* handle, const uint8_t dispoff);
extern void microondas_selector(const Microondas* handle, const uint8_t digito);






/*! 
This function has to set up timers for the time events that are required by the state machine.
It will be called for each time event that is relevant for a state when a state will be entered.
\param evid An unique identifier of the event.
\time_ms The time in milliseconds
\periodic Indicates the the time event must be raised periodically until the timer is unset 
*/
extern void microondas_set_timer(Microondas* handle, const sc_eventid evid, const sc_integer time_ms, const sc_boolean periodic);

/*! 
This function has to unset timers for the time events that are required by the state machine.
It will be called for each time event that is relevant for a state when a state will be left.
\param evid An unique identifier of the event.
*/
extern void microondas_unset_timer(Microondas* handle, const sc_eventid evid);



#ifdef __cplusplus
}
#endif 

#endif /* MICROONDAS_REQUIRED_H_ */
